name: tests

on:
  push:
    branches:
      - '*' # Run on all branches
  pull_request:
    branches:
      - '*' # Run on all branches

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.7"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install GreynirCorrect
      run: |
        python -m pip install --upgrade pip wheel setuptools pytest
        python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer
        python -m pip install git+https://github.com/mideind/GreynirPackage#egg=reynir
        # The neural sentence classifier doesn't work with pypy so don't try to install it
        if [ "${{ matrix.python-version }}" == "pypy-3.7" ]; then
          python -m pip install -e .
        else
          python -m pip install -e .[sentence_classifier]
        fi
    - name: Typecheck with mypy
      run: |
        if [ "${{ matrix.python-version }}" == "3.7" ]; then python -m pip install mypy; fi
        if [ "${{ matrix.python-version }}" == "3.7" ]; then mypy --ignore-missing-imports --python-version=3.7 src/reynir_correct; fi
    - name: Test with pytest
      run: |
        python -m pytest
